SET SERVEROUTPUT ON;
BEGIN

INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Citroën', 'Berlingo', '4562ARF');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Dacia', 'Dokker Van', '4897BGT');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Fiat', 'Doblo Cargo', '7895CFT');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Citroën', 'Berlingo', '6205GHT');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Fiat', 'Doblo Cargo', '9001AAA');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Dacia', 'Dokker Van', '6524DFG');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Ford', 'Transit Connect', '8452RTY');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Fiat', 'Doblo Cargo', '7825DRV');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Opel', 'Combo Cargo', '3259CVA');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Ford', 'Transit Connect', '7841LKU');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('CAMION', 'Man', 'L-2000', '6521EFT');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Ford', 'Transit Connect', '9963DDD');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('CAMION', 'Renault', 'Mascot', '6321FGB');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Dacia', 'Dokker Van', '4562EDC');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('CAMION', 'Man', 'L-2000', '1235NHJ');
INSERT INTO VEHICULOS (TIPO, MARCA, MODELO, MATRICULA) VALUES ('FURGONETA', 'Dacia', 'Dokker Van', '1458TFV');

COMMIT;
DBMS_OUTPUT.PUT_LINE('Se han insertado 16 nuevos registros.');

EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR EN LA TRANSACCION: '|| SQLERRM);
DBMS_OUTPUT.PUT_LINE('SE DESHACEN LAS MODIFICACIONES');
ROLLBACK;

END;





