SET SERVEROUTPUT ON;
BEGIN

INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (3, 7, 2, '11/04/2021', 'Avenida de Montañana 114, Zaragoza', 0.3, 6.5, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (3, 7, 3, '13/04/2021', 'Avenida de Montañana 12, Zaragoza', 0.3, 12.5, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (5, 9, 8, '16/04/2021', 'Calle El Coso, 56, Zaragoza', 0.6, 5.6, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (5, 9, 8, '12/04/2021', 'Calle El Coso, 68, Zaragoza', 0.6, 3.5, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (3, 7, 6, '12/04/2021', 'Calle Emilia Pardo Bazán 14, Zaragoza', 1, 3.5, 0, 0);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (3, 7, 7, '13/04/2021', 'Calle Emilia Pardo Bazán 2, Zaragoza', 1, 12.5, 0, 0);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (5, 9, 9, '13/04/2021', 'Calle Escritor Mújica Laínez 29, Zaragoza', 2, 12, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (5, 9, 9, '12/04/2021', 'Calle Escritor Mújica Laínez 48, Zaragoza', 2, 6.5, 0, 0);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (6, 8, 17, '11/04/2021', 'Calle Isla La Graciosa 15, Zaragoza', 0.8, 5.6, 0, 0);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (6, 8, 15, '09/04/2021', 'Calle Isla La Graciosa 6, Zaragoza', 0.8, 3.5, 0, 0);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (6, 8, 13, '15/04/2021', 'Calle La Prima Angélica 2, Zaragoza', 0.56, 12.5, 0, 0);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (6, 8, 14, '12/04/2021', 'Calle La Prima Angélica 26, Zaragoza', 0.56, 6.5, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (7, 1, 12, '09/04/2021', 'Calle Padre Elías Limonar 17, Zaragoza', 0.35, 3.5, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (7, 1, 11, '15/04/2021', 'Calle Padre Elías Limonar 8B, Zaragoza', 0.35, 12.5, 0, 0);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (9, 2, 12, '11/04/2021', 'Calle Pedro Porter 24, Zaragoza', 0.5, 5.6, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (9, 2, 11, '13/04/2021', 'Calle Pedro Porter 56, Zaragoza', 0.5, 14, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (9, 3, 10, '12/04/2021', 'Calle Santuario de Rodanas 3, Zaragoza', 5, 12, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (9, 3, 1, '11/04/2021', 'Calle Santuario de Rodanas 5, Zaragoza', 5, 6.5, 0, 0);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (1, 6, 1, '13/04/2021', 'Calle Valdealgorfa 2, Zaragoza', 1.2, 14, 0, 0);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (1, 6, 4, '12/04/2021', 'Calle Valdealgorfa 63, Zaragoza', 1.2, 12, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (1, 6, 9, '13/04/2021', 'Paseo de la Ribera 46, Zaragoza', 4, 12, 1, 1);
INSERT INTO PEDIDOS (VEHICULO_ID, REPARTIDOR_ID, CLIENTE_ID, FECHA_ENVIO, DIRECCION, PESO, PRECIO, FRAGIL,URGENTE) VALUES (1, 6, 5, '11/04/2021', 'Paseo de la Ribera 55, Zaragoza', 4, 14, 1, 1);

COMMIT;
DBMS_OUTPUT.PUT_LINE('Se han insertado 22 nuevos registros.');

EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR EN LA TRANSACCION: '|| SQLERRM);
DBMS_OUTPUT.PUT_LINE('SE DESHACEN LAS MODIFICACIONES');
ROLLBACK;

END;